/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContainerRouteRouteImport } from './routes/_container/route'
import { Route as ContainerIndexRouteImport } from './routes/_container/index'
import { Route as ContainerTestRouteImport } from './routes/_container/test'
import { Route as ContainerReportRouteImport } from './routes/_container/report'
import { Route as ContainerListRouteImport } from './routes/_container/list'
import { Route as ContainerAddRouteImport } from './routes/_container/add'

const ContainerRouteRoute = ContainerRouteRouteImport.update({
  id: '/_container',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainerIndexRoute = ContainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContainerRouteRoute,
} as any)
const ContainerTestRoute = ContainerTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ContainerRouteRoute,
} as any)
const ContainerReportRoute = ContainerReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ContainerRouteRoute,
} as any)
const ContainerListRoute = ContainerListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ContainerRouteRoute,
} as any)
const ContainerAddRoute = ContainerAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ContainerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/add': typeof ContainerAddRoute
  '/list': typeof ContainerListRoute
  '/report': typeof ContainerReportRoute
  '/test': typeof ContainerTestRoute
  '/': typeof ContainerIndexRoute
}
export interface FileRoutesByTo {
  '/add': typeof ContainerAddRoute
  '/list': typeof ContainerListRoute
  '/report': typeof ContainerReportRoute
  '/test': typeof ContainerTestRoute
  '/': typeof ContainerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_container': typeof ContainerRouteRouteWithChildren
  '/_container/add': typeof ContainerAddRoute
  '/_container/list': typeof ContainerListRoute
  '/_container/report': typeof ContainerReportRoute
  '/_container/test': typeof ContainerTestRoute
  '/_container/': typeof ContainerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/add' | '/list' | '/report' | '/test' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/add' | '/list' | '/report' | '/test' | '/'
  id:
    | '__root__'
    | '/_container'
    | '/_container/add'
    | '/_container/list'
    | '/_container/report'
    | '/_container/test'
    | '/_container/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ContainerRouteRoute: typeof ContainerRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_container': {
      id: '/_container'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ContainerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_container/': {
      id: '/_container/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ContainerIndexRouteImport
      parentRoute: typeof ContainerRouteRoute
    }
    '/_container/test': {
      id: '/_container/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof ContainerTestRouteImport
      parentRoute: typeof ContainerRouteRoute
    }
    '/_container/report': {
      id: '/_container/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ContainerReportRouteImport
      parentRoute: typeof ContainerRouteRoute
    }
    '/_container/list': {
      id: '/_container/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ContainerListRouteImport
      parentRoute: typeof ContainerRouteRoute
    }
    '/_container/add': {
      id: '/_container/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof ContainerAddRouteImport
      parentRoute: typeof ContainerRouteRoute
    }
  }
}

interface ContainerRouteRouteChildren {
  ContainerAddRoute: typeof ContainerAddRoute
  ContainerListRoute: typeof ContainerListRoute
  ContainerReportRoute: typeof ContainerReportRoute
  ContainerTestRoute: typeof ContainerTestRoute
  ContainerIndexRoute: typeof ContainerIndexRoute
}

const ContainerRouteRouteChildren: ContainerRouteRouteChildren = {
  ContainerAddRoute: ContainerAddRoute,
  ContainerListRoute: ContainerListRoute,
  ContainerReportRoute: ContainerReportRoute,
  ContainerTestRoute: ContainerTestRoute,
  ContainerIndexRoute: ContainerIndexRoute,
}

const ContainerRouteRouteWithChildren = ContainerRouteRoute._addFileChildren(
  ContainerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ContainerRouteRoute: ContainerRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
