/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContainerRouteRouteImport } from './routes/_container/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContainerTestRouteImport } from './routes/_container/test'

const ContainerRouteRoute = ContainerRouteRouteImport.update({
  id: '/_container',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainerTestRoute = ContainerTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ContainerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof ContainerTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof ContainerTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_container': typeof ContainerRouteRouteWithChildren
  '/_container/test': typeof ContainerTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test'
  id: '__root__' | '/' | '/_container' | '/_container/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainerRouteRoute: typeof ContainerRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_container': {
      id: '/_container'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ContainerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_container/test': {
      id: '/_container/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof ContainerTestRouteImport
      parentRoute: typeof ContainerRouteRoute
    }
  }
}

interface ContainerRouteRouteChildren {
  ContainerTestRoute: typeof ContainerTestRoute
}

const ContainerRouteRouteChildren: ContainerRouteRouteChildren = {
  ContainerTestRoute: ContainerTestRoute,
}

const ContainerRouteRouteWithChildren = ContainerRouteRoute._addFileChildren(
  ContainerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainerRouteRoute: ContainerRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
